// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovMvir_qa4ZHxPOkBuoQBblOYADMIYVM',
    appId: '1:851716129446:web:90b8180a9e8c62dcae2a67',
    messagingSenderId: '851716129446',
    projectId: 'portfolio-3ba07',
    authDomain: 'portfolio-3ba07.firebaseapp.com',
    storageBucket: 'portfolio-3ba07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_KCJvCMVkUg1Z2dFthivSXnhwHV4HxoQ',
    appId: '1:851716129446:android:9180fa9d990d3670ae2a67',
    messagingSenderId: '851716129446',
    projectId: 'portfolio-3ba07',
    storageBucket: 'portfolio-3ba07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-8ySHg_JF7-fafKGWe2Ve7jof6XXKAA',
    appId: '1:851716129446:ios:7eeaea449c3b7554ae2a67',
    messagingSenderId: '851716129446',
    projectId: 'portfolio-3ba07',
    storageBucket: 'portfolio-3ba07.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAovMvir_qa4ZHxPOkBuoQBblOYADMIYVM',
    appId: '1:851716129446:web:b0cacd7f0d2af883ae2a67',
    messagingSenderId: '851716129446',
    projectId: 'portfolio-3ba07',
    authDomain: 'portfolio-3ba07.firebaseapp.com',
    storageBucket: 'portfolio-3ba07.firebasestorage.app',
  );

}